version: '3'
services:
  superset:
    image: apache/superset
    environment:
      - SUPERSET_LOAD_EXAMPLES=yes
    ports:
      - "8088:8088"
    volumes:
      - "/c/Users/Administrator/Desktop/AiML/AiML-marketing-analytics-dashboard/superset:/home/superset"
    command: ["superset", "run", "-p", "8088", "-h", "0.0.0.0"]
    depends_on:
      - db
    networks:
      - superset_network
  db:
    image: postgres:12
    environment:
      - POSTGRES_USER=superset
      - POSTGRES_PASSWORD=superset
      - POSTGRES_DB=superset
    volumes:
      - "/c/Users/Administrator/Desktop/AiML/AiML-marketing-analytics-dashboard/postgres:/var/lib/postgresql/data"
    networks:
      - superset_network
networks:
  superset_network:
    driver: bridge
