services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: MarketingAnalyticsDB
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  redis:
    image: redis:5.0
  worker:
    image: redash/redash:latest
    command: worker
    environment:
      REDASH_DATABASE_URL: postgresql://admin:admin@host.docker.internal:5432/MarketingAnalyticsDB
      REDASH_REDIS_URL: redis://redis:6379/0
  web:
    image: redash/redash:latest
    command: server
    ports:
      - 5000:5000
    environment:
      REDASH_DATABASE_URL: postgresql://admin:admin@host.docker.internal:5432/MarketingAnalyticsDB
      REDASH_REDIS_URL: redis://redis:6379/0
      REDASH_WEB_WORKERS: 4
volumes:
  postgres-data:
